# vim bindings:
bindkey -v
# paru -S zsh-vi-mode
source $HOME/.config/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# git
autoload -Uz vcs_info
zstyle ':vcs_info:git*' formats " (%b)"
precmd() { vcs_info }

setopt prompt_subst
PROMPT='%F{green}%3~%F{yellow}$vcs_info_msg_0_ %f%# '

# aliases
alias sourcezsh="source ~/.zshrc"

alias ls="ls --color"
alias la="ls -a --color"
alias ll="ls -lah --color"
alias grep="grep --color"
alias cat="bat"

alias nv="nvim"
# alias nv="$HOME/appimages/nvim-nightly.appimage"

alias gpuusage="watch -n 1 nvidia-smi"

function mkcd() {
    mkdir $1 && cd $1
}

# PATH config
export PATH="$HOME/.local/bin:$HOME/.local/nvim/bin:$PATH" # ~/.local/bin
export PATH="$HOME/.dotnet/tools:$PATH"
